version: '3'

services:
  threading:
    build: ./thread
    volumes:
      - ./thread:/usr/src/app
    ports:
      - 1010:1000
  processing:
    build: ./process
    volumes:
      - ./process:/usr/src/app
    ports:
      - 3010:3000

  # result:
  #     build: ./result
  #     volumes:
  #       - ./result:/usr/src/app
  #     ports:
  #       - 1020:1000
  #     depends_on:
  #       - threading
